### ISSUE TITLE
Launch images and text

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/design-a-space-telescope#5]
Replace youTube videos with basic stills or animation. Need to think about what to show.

**Comment by chrisnorth** [comment]
Stages:
* Launch
* Achieved orbit
* Mirror deployment
* Cooling System on
* Instruments on
* Instruments working

**Comment by slowe** [comment]
We will step through each of these stages.

**Comment by slowe** [comment]
I've created an image of each launch site so that your chosen rocket launches from your chosen site. I've created an exhaust effect for the launch.

**Comment by slowe** [comment]
Some screenshots of launches from Pletesk, Xichang and French Guiana
![screen shot 2015-03-31 at 13 44 44](https://cloud.githubusercontent.com/assets/299787/6919121/39f8bd14-d7ac-11e4-8272-a5b3723e6923.png)
![screen shot 2015-03-31 at 13 46 05](https://cloud.githubusercontent.com/assets/299787/6919134/530b4d44-d7ac-11e4-95ae-08e2220e12c3.png)
![screen shot 2015-03-31 at 13 47 10](https://cloud.githubusercontent.com/assets/299787/6919157/7f631552-d7ac-11e4-988f-e086703ef358.png)

Each consists of a foreground and background image. The animated rocket exhaust is sandwiched between the two on a canvas element.

**Comment by chrisnorth** [comment]
Bloody hell - those are amazing!

**Comment by slowe** [comment]
I haven't done the Carrier Aircraft. As it isn't a vertical launch I'm a bit uncertain what the best method is to deal with it.

**Comment by slowe** [comment]
For completeness here is Tanegashima, Satish Dhawan, Baikonur, Vandenberg and Kennedy...
![screen shot 2015-03-31 at 14 01 08](https://cloud.githubusercontent.com/assets/299787/6919387/6f2841c4-d7ae-11e4-89fe-7777fce1a540.png)
![screen shot 2015-03-31 at 14 00 27](https://cloud.githubusercontent.com/assets/299787/6919390/71da0ca4-d7ae-11e4-84f8-f1c74e24ded8.png)
![screen shot 2015-03-31 at 14 00 03](https://cloud.githubusercontent.com/assets/299787/6919392/7449c5b0-d7ae-11e4-9d97-0b4d8af173ce.png)
![screen shot 2015-03-31 at 13 59 33](https://cloud.githubusercontent.com/assets/299787/6919393/75ece064-d7ae-11e4-800b-bf87f3c3ef82.png)
![screen shot 2015-03-31 at 13 59 09](https://cloud.githubusercontent.com/assets/299787/6919398/77a12a1e-d7ae-11e4-8dbb-e4bae1e40c35.png)

**Comment by chrisnorth** [comment]
It would be a special case, certainly, but perhaps dropping down and
launching horizontally from below a plane?

Or view it top-down and fly off the top of the page, that way it's still
vertical? Foreground layer is the plane, background layer is the sea?

+----------------------------------------------------------+
| Dr Chris North
| Research Associate, Undergraduate Admissions Tutor &
| Community Engagement Coordinator
| School of Physics and Astronomy, Cardiff University
| chris.north@astro.cf.ac.uk
| +44 (0)29 208 70537
+----------------------------------------------------------+

**Comment by slowe** [comment]
Top down with sea below sounds good. Would we go with this design plane http://www.space.com/18747-stratolaunch-orbital-sciences-replaces-spacex.html or this one http://www.nasa.gov/mission_pages/nustar/multimedia/nustarC20120110.html ?

**Comment by chrisnorth** [comment]
Although the jumbo jet is what the Pegasus uses, the Stratolaunch plane
looks cooler and probably better for showing the animation - so I think
that would be best.

+----------------------------------------------------------+
| Dr Chris North
| Research Associate, Undergraduate Admissions Tutor &
| Community Engagement Coordinator
| School of Physics and Astronomy, Cardiff University
| chris.north@astro.cf.ac.uk
| +44 (0)29 208 70537
+----------------------------------------------------------+

**Comment by slowe** [comment]
It has taken several days of solid work but I think I've finally managed to add all the stages listed above.

**Comment by slowe** [comment]
Done.
